services:
  - type: web
    name: mirai-bot
    runtime: node
    repo: https://github.com/raihan9099/Milow/repo
    plan: free
    region: oregon
    branch: 'main'
    buildCommand: npm install
    startCommand: node mirai.js
    autoDeploy: 'true'
    envVars:
      - key: FB_APP_STATE
        sync: 'true'
      - key: BOT_PREFIX
        value: "!"
      - key: OWNER_NAME
        value: "Maisha"
      - key: SIMSIMI_API_KEY
        sync: true
      - key: DATABASE_URL
        fromDatabase:
          name: mirai-db
          property: connectionString
      - fromGroup: mirai-settings

databases:
  - name: mirai-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: public

envVarGroups:
  - name: mirai-settings
    envVars:
      - key: LANGUAGE
        value: bn
      - key: OWNER_ID
        value: "1000XXXXXXXXXXX"
